### PR TITLE
npm stuff

### PR DESCRIPTION
**Pull request by mattly**
presenting this as an alternative to #62 – I'd rather have `--depth 0` than `--parseable`.

I'm going to add outdated/upgrade support while I'm in here.

### CODE REVIEW

**Comment by mattly** [comment]
:cry: 

bork fish 2016-03-26 20-56-23

**Comment by frdmn** [comment]
@mattly I've just pulled the latest changes, and it seems that the NPM type broke for me:

```shell
❯  bork2 git:(master) ./bin/bork satisfy /Users/jonas/.dotfiles/borkfiles/npm.bork
npm ERR! addLocal Could not install /private/var/folders/w8/7kxbcq6d5k57r18y0sbsbmfr0000gn/T/npm.44984/package
ok: npm npm
npm ERR! addLocal Could not install /private/var/folders/w8/7kxbcq6d5k57r18y0sbsbmfr0000gn/T/npm.44984/package
ok: npm bower
npm ERR! addLocal Could not install /private/var/folders/w8/7kxbcq6d5k57r18y0sbsbmfr0000gn/T/npm.44984/package
ok: npm diff-so-fancy
[...]
```

Here's the full debug output: http://paste.frd.mn/obawe

**Comment by mattly** [comment]
Ugh. What versions of node and npm do you have?

On Sun, Mar 27, 2016 at 04:16 Jonas Friedmann <notifications@github.com>
wrote:

> @mattly <https://github.com/mattly> I've just pulled the latest changes,
> and it seems that the NPM type broke for me:
>
> ❯  bork2 git:(master) ./bin/bork satisfy /Users/jonas/.dotfiles/borkfiles/npm.bork
> npm ERR! addLocal Could not install /private/var/folders/w8/7kxbcq6d5k57r18y0sbsbmfr0000gn/T/npm.44984/package
> ok: npm npm
> npm ERR! addLocal Could not install /private/var/folders/w8/7kxbcq6d5k57r18y0sbsbmfr0000gn/T/npm.44984/package
> ok: npm bower
> npm ERR! addLocal Could not install /private/var/folders/w8/7kxbcq6d5k57r18y0sbsbmfr0000gn/T/npm.44984/package
> ok: npm diff-so-fancy
> [...]
>
> Here's the full debug output: http://paste.frd.mn/obawe
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mattly/bork/pull/64#issuecomment-202041040>
>
-- 
Matthew Lyon
lyonheart.us | @mattly

**Comment by frdmn** [comment]
@mattly Sorry to persistently bother you with this... Here's my node and npm versions:

```shell
❯  ~  npm -v
3.8.0
❯  ~  node -v
v5.9.1
``` 

I also notice that running `npm outdated -g` ends up in the same error:

```shell
❯  ~  npm outdated -g
npm ERR! addLocal Could not install /private/var/folders/w8/7kxbcq6d5k57r18y0sbsbmfr0000gn/T/npm.44984/package
Package            Current  Wanted  Latest  Location
canibekikked         1.4.0   1.5.1   1.5.1
electron-prebuilt  0.36.10  0.37.2  0.37.2
grunt-cli           0.1.13   1.1.0   1.1.0
```

I'm going to research this and let you know, as soon as I find anything :)

**Comment by frdmn** [comment]
@mattly Running `npm install npm@latest -g` to bring npm to version `3.8.3` fixed the issue for me:

```shell
❯  bork git:(master) npm -v
3.8.3
❯  bork git:(master) ./bin/bork satisfy /Users/jonas/.dotfiles/borkfiles/npm.bork
ok: npm npm
```

**Comment by mattly** [comment]
... so it looks like it's a bug in npm that, even if it wasn't fixed, we wouldn't be able to work around. :welp:

**Comment by frdmn** [comment]
@mattly yeah, it seems so. Well, at least we know about this in case of further occurance. :)

**Pull request merged**
