### PR TITLE
types/cash.sh #status was raising $STATUS_UNSUPPORTED_PLATFORM.

### PR DESCRIPTION
**Pull request by hayduke19us**
The error was on `brew cask 2`, returning -gt 0 every time. 
I noticed the failure when trying to `ok cask something`.

### CODE REVIEW

**Comment by frdmn** [comment]
I'm not really sure what the "brew cask 2" was for originally, but apparently @mattly added it as workaround because it "suddenly" stopped working (see 2941da771e3cb545fec6c3f8ce4ad42613164f84 and 60312fef7f089cf21f9ddfdd9b3ee3d8a21d0697) some time ago.

I think it would be better to revert those commits to restore the "original" state again. Perhaps that also fixes the bats Travis tests.

Thanks a lot for the PR already! :+1:

**Comment by frdmn** [comment]
@hayduke19us I just did some test and the revert of said commits also fixes the travis tests:

https://travis-ci.org/frdmn/bork/builds/100116974

My changes: 

https://github.com/frdmn/bork/compare/b8ed293026ce7a224dec78e583a7fc95e979221b...master

**Comment by mattly** [comment]
hey, thanks for this, I'll take a look soon. I've been really busy with work recently. I'm not sure what was going on with the original code here anymore... though I think I mocked the presence of brew such that the test would pass on a non-mac platform, just as I had to mock f.e. apt or the like.

**Comment by mattly** [comment]
Oddly enough, I still can't reproduce any actual problems caused by this, though I know it's been problematic. Anyway, I ripped out the redirect of stderr & stdout so that there's nothing weird going on with the tests, and I'm happy with the behavior.

Thanks for bringing this to my attention!

**Comment by hayduke19us** [comment]
Hmm. Yeah it was weird. I was setting up a new work machine. El Capitan, with the newest brew version.

brew 0.9.5 (git revision 81f8; last commit 2016-01-09), brew cask 0.60

My old machine works just fine. Yosemite, and brew git revision d6b31, brew cask 0.53.


On January 14, 2016 at 9:17:17 PM, Matthew Lyon (notifications@github.com) wrote:

Closed #48.

**Pull request closed without merging**
